#!/usr/bin/env python3
r"""render_meta.py — construct per-problem effort markers (difficulty stars /
point values) FROM the verify JSON, so the printed markers can never disagree
with the verified difficulty tags.

Why this exists: SKILL.md mandates a "difficulty" tag on every problem and
verify.py carries it as a reporting field, but nothing brought that verified
data to the student page — quiz sheets shipped without the point values that
let a student budget time and a parent grade. Hand-typing "(3 pts)" or star
glyphs would be the same retyping-drift class the figure renderer kills, so
markers follow the \probfig construction pattern instead: this script emits
macro bodies from the JSON and the checkers ban hand-typed markers outright.

Usage: render_meta.py <verify_<stem>.json> [out.tex]
Default output: meta_<stem>.tex next to the input (verify_ prefix -> meta_,
mirroring render_figures.py). Stdlib-only on purpose — build.sh runs it with
plain python3, no sympy needed to render an integer.

The emitted file is fully SELF-CONTAINED: per-problem bodies AND the
dispatchers (\probmeta, \probpts, \totalpoints) live here, exactly like the
figs file, so it works even in a document that hand-rolls its preamble.
Its only dependency is amssymb for \bigstar (templates/worksheet-preamble.tex
already loads it).

Both modes are emitted for every problem; a document uses exactly ONE
(\probpts{N} point values for quizzes, \probmeta{N} stars for practice
sheets — see SKILL.md steps 1 and 3). \totalpoints is the computed sum of
difficulties, never hand-typed.

This is the one place difficulty becomes gating: every problem must carry an
integer difficulty in 1..5, or the run fails listing the offending ids —
verify.py itself never range-checks the tag ("reporting, never gating" stays
true there), and a difficulty of 7 would otherwise render seven stars.

Exit 0: meta file written. Exit 1: invalid input — no file is written,
because a garbage marker is worse than no marker.
"""

import json
import os
import sys


def collect_difficulties(data):
    """{id -> difficulty} or raises ValueError listing offending ids.

    Multi-entry ids must agree on their tag — two entries for problem 4
    declaring 3 and 4 stars is a data conflict, not a choice.
    """
    by_id = {}
    bad = []
    for p in data.get("problems", []):
        if not isinstance(p, dict) or not isinstance(p.get("id"), int):
            continue
        pid = p["id"]
        d = p.get("difficulty")
        if isinstance(d, bool) or not isinstance(d, int) or not 1 <= d <= 5:
            bad.append(pid)
            continue
        if pid in by_id and by_id[pid] != d:
            bad.append(pid)
            continue
        by_id[pid] = d
    n = data.get("problem_count")
    ids = range(1, n + 1) if isinstance(n, int) and n > 0 else sorted(by_id)
    missing = [i for i in ids if i not in by_id and i not in bad]
    bad.extend(missing)
    if bad:
        raise ValueError(
            f"problem id(s) {sorted(set(bad))} lack an integer difficulty in "
            "1..5 (missing, out of range, non-integer, or conflicting across "
            "entries). Difficulty tags become student-visible through "
            "\\probmeta/\\probpts — fix the tag in the verify JSON; never "
            "hand-type a marker.")
    return {i: by_id[i] for i in ids}


def render(data, src_name, out_name):
    """The emitted meta file text — deterministic, ASCII-only."""
    diffs = collect_difficulties(data)
    lines = [
        f"% {out_name} -- GENERATED by scripts/render_meta.py from "
        f"{src_name}.",
        "% Do not edit: markers are constructed from the verified difficulty",
        "% tags so they cannot drift. Re-run render_meta.py after any JSON",
        "% edit (a stale file is caught by check_prose_consistency --meta).",
        "% Requires amssymb for \\bigstar (worksheet-preamble.tex loads it).",
        "%",
        "% Use exactly ONE mode per document, on every problem:",
        "%   \\probpts{N}  -- \"(D pts)\" point values (quiz default)",
        "%   \\probmeta{N} -- difficulty stars (practice sheets, opt-in)",
        "",
    ]
    for pid in diffs:
        d = diffs[pid]
        stars = "\\bigstar" * d
        lines.append(f"% >>> probmeta {pid}")
        lines.append(
            f"\\expandafter\\newcommand\\csname probmeta{pid}\\endcsname"
            f"{{\\;{{\\footnotesize\\ensuremath{{{stars}}}}}}}")
        lines.append(
            f"\\expandafter\\newcommand\\csname probpts{pid}\\endcsname"
            f"{{\\;{{\\footnotesize({d} pts)}}}}")
    total = sum(diffs.values())
    lines += [
        "",
        "% dispatchers -- place \\probmeta{N}/\\probpts{N} at the end of "
        "problem N's stem",
        "\\newcommand{\\probmeta}[1]{\\csname probmeta#1\\endcsname}",
        "\\newcommand{\\probpts}[1]{\\csname probpts#1\\endcsname}",
        f"\\newcommand{{\\totalpoints}}{{{total}}}",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    if len(argv) not in (2, 3):
        print("Usage: render_meta.py <verify_TOPIC_DATE.json> [out.tex]",
              file=sys.stderr)
        return 1
    json_path = argv[1]
    base = os.path.basename(json_path)
    stem = base[len("verify_"):] if base.startswith("verify_") else base
    stem = stem[:-len(".json")] if stem.endswith(".json") else stem
    out_path = argv[2] if len(argv) == 3 else \
        os.path.join(os.path.dirname(os.path.abspath(json_path)),
                     f"meta_{stem}.tex")
    try:
        data = json.load(open(json_path))
    except (OSError, json.JSONDecodeError) as e:
        print(f"Error reading {json_path}: {e}", file=sys.stderr)
        return 1
    try:
        text = render(data, base, os.path.basename(out_path))
    except ValueError as e:
        print(f"render_meta.py: {e}", file=sys.stderr)
        return 1
    with open(out_path, "w") as f:
        f.write(text)
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
